import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/contexts/AuthContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WebSocketProvider from "@/contexts/WebSocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <html lang="en">
        <body className={`dark ${inter.className}`}>
            <AuthProvider>
                <WebSocketProvider>
                    <Toaster />
                    {children}
                </WebSocketProvider>
            </AuthProvider>
        </body>
    </html>
  );
}
